- name: Test user add
  hosts: all
  become: yes
  become_user: vagrant
#   ansible_become_user: root
#   ansible_ssh_user: vagrant
  gather_facts: no
  tasks:
    - name: Add user
      user:
        name: johnd
        group: wheel
        uid: 1032
